### PR TITLE
HomeWork#2 Take dependency from own github repository.

### PR DESCRIPTION
**Pull request by Muao**

### CODE REVIEW

**Review by dinamio — CHANGES_REQUESTED** [review]
Where is your com.muao.quicksort project code?

**Comment by Muao** [comment]
It's[ here](https://github.com/Muao/quicksort/blob/master/src/main/java/com/muao/QuickSort.java).
In branch mvn-repo just repo, only with jar, in master - code.

**Comment by dinamio** [comment]
Can you add QuickSort to pull request, to not forget about it?

**Comment by Muao** [comment]
I don't know, how I can add external project to pull request. It's already in pom.xml in pull request.

**Review by dinamio — APPROVED** [review]

**Pull request merged**
